#+title: liblog
#+options: toc:nil
#+startup: showeverything
#+author: 8dcc

*Personal C99 logging library.*

#+TOC: headlines 2

* Description

This simple library consists of a main =log_write= function defined in [[file:src/liblog.c][liblog.c]],
and the following wrappers:

1. =log_dbg=
2. =log_inf=
3. =log_wrn=
4. =log_err=
5. =log_ftl=

These macros, defined in [[file:src/liblog.h][liblog.h]], take a variable list of arguments (hence the
C99 requirement) that must be valid for =printf=.

The =log_write= function prints the following information:

1. If =LOG_DATE= is defined, the current year, month and day.
2. The current hour, minute and second.
3. A tag, determined by the wrapper used. If =LOG_COLOR= is defined, a different
   color will be used depending on the tag.
4. The current function name. If =LOG_COLOR= is defined, the ASCII escape sequence
   =LOG_COLOR_DIM= will be used.
5. The user format string that was passed to the wrapper.

These macros should be defined in the =log.h= header, or by calling the compiler
with =-D...= arguments.

* Building the example

To try the example, simply clone the repository, compile it, and run
=liblog-test.out=. Please see [[file:src/main.c][main.c]] for an example on how to use it.

#+begin_src console
$ git clone https://github.com/8dcc/liblog
$ cd liblog
$ make
$ ./liblog-test.out
#+end_src
